apiVersion: 1.0
kind: CronWorkflow
metadata:
  name: courses-cron-work-flow
spec:
  schedule: "* * 7 * *"
  workflowSpec:
    entrypoint: get-courses-in-HTML
    templates:
    - name: get-courses-in-HTML
      inputs:
        parameters:
        - name: keyword
      container:
        image: get_courses
        args: ["{{inputs.parameters.keyword}}"]
    - name: convert-HTML-to-raw-data
      inputs:
        parameters:
        - name: html-file-path
      container:
        image: convert-to-raw-data
        args: ["{{inputs.parameters.html-file-path}}"]
      dependencies:
      - get-courses-in-HTML
    - name: update-courses-records
      inputs:
        parameters:
        - name: existing-courses-file-path
      container:
        image: update-courses-records
        args: ["{{inputs.existing-courses-file-path}}"]
      dependencies:
      - convert-HTML-to-raw-data
    -name: integration-tests
      inputs:
        parameters:
        - name: raw-data-path
      container:
        image: test_courses
        args: ["{{inputs.parameters.keyword}}", "--raw-data", "inputs.parameters.raw-data"]
      dependencies:
      - convert-HTML-to-raw-data